// Code generated by github.com/tinylib/msgp DO NOT EDIT.

package tbmodels

import (
	"github.com/tinylib/msgp/msgp"
)

// DecodeMsg implements msgp.Decodable
func (z *WebsocketConfigSnapshot) DecodeMsg(dc *msgp.Reader) (err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, err = dc.ReadMapHeader()
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, err = dc.ReadMapKeyPtr()
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i":
			z.SourceInstanceID, err = dc.ReadString()
			if err != nil {
				err = msgp.WrapError(err, "SourceInstanceID")
				return
			}
		case "s":
			var zb0002 uint32
			zb0002, err = dc.ReadMapHeader()
			if err != nil {
				err = msgp.WrapError(err, "Settings")
				return
			}
			if z.Settings == nil {
				z.Settings = make(map[string]string, zb0002)
			} else if len(z.Settings) > 0 {
				clear(z.Settings)
			}
			for zb0002 > 0 {
				zb0002--
				var za0001 string
				za0001, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Settings")
					return
				}
				var za0002 string
				za0002, err = dc.ReadString()
				if err != nil {
					err = msgp.WrapError(err, "Settings", za0001)
					return
				}
				z.Settings[za0001] = za0002
			}
		case "u":
			var zb0003 uint32
			zb0003, err = dc.ReadArrayHeader()
			if err != nil {
				err = msgp.WrapError(err, "Users")
				return
			}
			if cap(z.Users) >= int(zb0003) {
				z.Users = (z.Users)[:zb0003]
			} else {
				z.Users = make([]User, zb0003)
			}
			for za0003 := range z.Users {
				err = z.Users[za0003].DecodeMsg(dc)
				if err != nil {
					err = msgp.WrapError(err, "Users", za0003)
					return
				}
			}
		case "r":
			z.Revision, err = dc.ReadUint64()
			if err != nil {
				err = msgp.WrapError(err, "Revision")
				return
			}
		case "v":
			z.SchemaVersion, err = dc.ReadUint8()
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		default:
			err = dc.Skip()
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	return
}

// EncodeMsg implements msgp.Encodable
func (z *WebsocketConfigSnapshot) EncodeMsg(en *msgp.Writer) (err error) {
	// map header, size 5
	// write "i"
	err = en.Append(0x85, 0xa1, 0x69)
	if err != nil {
		return
	}
	err = en.WriteString(z.SourceInstanceID)
	if err != nil {
		err = msgp.WrapError(err, "SourceInstanceID")
		return
	}
	// write "s"
	err = en.Append(0xa1, 0x73)
	if err != nil {
		return
	}
	err = en.WriteMapHeader(uint32(len(z.Settings)))
	if err != nil {
		err = msgp.WrapError(err, "Settings")
		return
	}
	for za0001, za0002 := range z.Settings {
		err = en.WriteString(za0001)
		if err != nil {
			err = msgp.WrapError(err, "Settings")
			return
		}
		err = en.WriteString(za0002)
		if err != nil {
			err = msgp.WrapError(err, "Settings", za0001)
			return
		}
	}
	// write "u"
	err = en.Append(0xa1, 0x75)
	if err != nil {
		return
	}
	err = en.WriteArrayHeader(uint32(len(z.Users)))
	if err != nil {
		err = msgp.WrapError(err, "Users")
		return
	}
	for za0003 := range z.Users {
		err = z.Users[za0003].EncodeMsg(en)
		if err != nil {
			err = msgp.WrapError(err, "Users", za0003)
			return
		}
	}
	// write "r"
	err = en.Append(0xa1, 0x72)
	if err != nil {
		return
	}
	err = en.WriteUint64(z.Revision)
	if err != nil {
		err = msgp.WrapError(err, "Revision")
		return
	}
	// write "v"
	err = en.Append(0xa1, 0x76)
	if err != nil {
		return
	}
	err = en.WriteUint8(z.SchemaVersion)
	if err != nil {
		err = msgp.WrapError(err, "SchemaVersion")
		return
	}
	return
}

// MarshalMsg implements msgp.Marshaler
func (z *WebsocketConfigSnapshot) MarshalMsg(b []byte) (o []byte, err error) {
	o = msgp.Require(b, z.Msgsize())
	// map header, size 5
	// string "i"
	o = append(o, 0x85, 0xa1, 0x69)
	o = msgp.AppendString(o, z.SourceInstanceID)
	// string "s"
	o = append(o, 0xa1, 0x73)
	o = msgp.AppendMapHeader(o, uint32(len(z.Settings)))
	for za0001, za0002 := range z.Settings {
		o = msgp.AppendString(o, za0001)
		o = msgp.AppendString(o, za0002)
	}
	// string "u"
	o = append(o, 0xa1, 0x75)
	o = msgp.AppendArrayHeader(o, uint32(len(z.Users)))
	for za0003 := range z.Users {
		o, err = z.Users[za0003].MarshalMsg(o)
		if err != nil {
			err = msgp.WrapError(err, "Users", za0003)
			return
		}
	}
	// string "r"
	o = append(o, 0xa1, 0x72)
	o = msgp.AppendUint64(o, z.Revision)
	// string "v"
	o = append(o, 0xa1, 0x76)
	o = msgp.AppendUint8(o, z.SchemaVersion)
	return
}

// UnmarshalMsg implements msgp.Unmarshaler
func (z *WebsocketConfigSnapshot) UnmarshalMsg(bts []byte) (o []byte, err error) {
	var field []byte
	_ = field
	var zb0001 uint32
	zb0001, bts, err = msgp.ReadMapHeaderBytes(bts)
	if err != nil {
		err = msgp.WrapError(err)
		return
	}
	for zb0001 > 0 {
		zb0001--
		field, bts, err = msgp.ReadMapKeyZC(bts)
		if err != nil {
			err = msgp.WrapError(err)
			return
		}
		switch msgp.UnsafeString(field) {
		case "i":
			z.SourceInstanceID, bts, err = msgp.ReadStringBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SourceInstanceID")
				return
			}
		case "s":
			var zb0002 uint32
			zb0002, bts, err = msgp.ReadMapHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Settings")
				return
			}
			if z.Settings == nil {
				z.Settings = make(map[string]string, zb0002)
			} else if len(z.Settings) > 0 {
				clear(z.Settings)
			}
			for zb0002 > 0 {
				var za0002 string
				zb0002--
				var za0001 string
				za0001, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Settings")
					return
				}
				za0002, bts, err = msgp.ReadStringBytes(bts)
				if err != nil {
					err = msgp.WrapError(err, "Settings", za0001)
					return
				}
				z.Settings[za0001] = za0002
			}
		case "u":
			var zb0003 uint32
			zb0003, bts, err = msgp.ReadArrayHeaderBytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Users")
				return
			}
			if cap(z.Users) >= int(zb0003) {
				z.Users = (z.Users)[:zb0003]
			} else {
				z.Users = make([]User, zb0003)
			}
			for za0003 := range z.Users {
				bts, err = z.Users[za0003].UnmarshalMsg(bts)
				if err != nil {
					err = msgp.WrapError(err, "Users", za0003)
					return
				}
			}
		case "r":
			z.Revision, bts, err = msgp.ReadUint64Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "Revision")
				return
			}
		case "v":
			z.SchemaVersion, bts, err = msgp.ReadUint8Bytes(bts)
			if err != nil {
				err = msgp.WrapError(err, "SchemaVersion")
				return
			}
		default:
			bts, err = msgp.Skip(bts)
			if err != nil {
				err = msgp.WrapError(err)
				return
			}
		}
	}
	o = bts
	return
}

// Msgsize returns an upper bound estimate of the number of bytes occupied by the serialized message
func (z *WebsocketConfigSnapshot) Msgsize() (s int) {
	s = 1 + 2 + msgp.StringPrefixSize + len(z.SourceInstanceID) + 2 + msgp.MapHeaderSize
	if z.Settings != nil {
		for za0001, za0002 := range z.Settings {
			_ = za0002
			s += msgp.StringPrefixSize + len(za0001) + msgp.StringPrefixSize + len(za0002)
		}
	}
	s += 2 + msgp.ArrayHeaderSize
	for za0003 := range z.Users {
		s += z.Users[za0003].Msgsize()
	}
	s += 2 + msgp.Uint64Size + 2 + msgp.Uint8Size
	return
}
